Improved wording of some OT questions and answers
sillsdev/Transcelerator pull request #130
Opened 2024-05-07 22:01 UTC by tombogle

This was especially to eliminate archaic KJV language

2024-05-16 20:58 UTC, andrew-polk requested changes

2024-05-16 20:58 UTC, andrew-polk commented on Transcelerator/TxlQuestions.xml
> +          <A>Instead, he was treat him as a hired servant. (40)</A>
Should be, "he was to treat..."

2024-05-16 20:59 UTC, andrew-polk reviewed
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/Transcelerator/130)* status: all files reviewed, 2 unresolved discussions (waiting on @tombogle)



<!-- Sent from Reviewable.io -->

2024-05-16 21:23 UTC, tombogle commented
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

*(Reviewable was [unable](https://github.com/Reviewable/Reviewable/issues/14) to map [this GitHub inline comment thread](https://github.com/sillsdev/Transcelerator/pull/130#discussion_r1604017236) to the right spot — sorry!)*

Should be, "he was to treat..."
</blockquote></details>

I'm so glad you're here.




<!-- Sent from Reviewable.io -->

2024-05-16 21:36 UTC, andrew-polk reviewed
It's been a struggle to get that large file to work well in the various review/comparison tools. I thought I had added a comment about a typo for angel (angwl), but I don't see it.

2024-05-17 15:03 UTC, andrew-polk approved these changes

2024-05-17 15:03 UTC, andrew-polk reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/Transcelerator/130)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)



<!-- Sent from Reviewable.io -->

2024-05-17 15:13 UTC, merged